import type { CSSProperties } from 'react'

export const styles = {
  aside: {
    display: 'flex',
    width: '280px',
    height: '100vh',
    flexDirection: 'column',
    borderRight: '1px solid #e7eaf0',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    position: 'sticky',
    top: 0,
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    height: '72px',
    flex: '0 0 72px',
    padding: '0 24px',
    borderBottom: '1px solid #e7eaf0',
    color: '#090b10',
    fontSize: '24px',
    fontWeight: 400,
    letterSpacing: '4px',
    lineHeight: 1,
  },
  brandAccent: {
    color: '#f59f18',
  },
  navigation: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: '14px',
    minHeight: 0,
    padding: '18px 18px 12px',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  sectionLabel: {
    color: '#b3bac6',
    fontSize: '15px',
    fontWeight: 400,
    letterSpacing: '0',
    lineHeight: 1,
    textTransform: 'uppercase',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    minHeight: '34px',
    padding: '0 12px 0 16px',
    borderRadius: '8px',
    color: '#727b8c',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: 1,
    textDecoration: 'none',
  },
  activeItem: {
    backgroundColor: '#f5f5f6',
    color: '#101114',
  },
  icon: {
    width: '18px',
    height: '18px',
    flex: '0 0 18px',
    objectFit: 'contain',
  },
  badge: {
    display: 'grid',
    width: '28px',
    height: '28px',
    marginLeft: 'auto',
    placeItems: 'center',
    borderRadius: '999px',
    backgroundColor: '#070707',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 700,
    lineHeight: 1,
  },
  proCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    flex: '0 0 auto',
    margin: '6px 18px 18px',
    padding: '18px',
    borderRadius: '12px',
    backgroundColor: '#fff9e9',
  },
  proTitle: {
    margin: 0,
    color: '#070707',
    fontSize: '18px',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  proText: {
    margin: 0,
    color: '#70798a',
    fontSize: '14px',
    lineHeight: 1.35,
  },
  proButton: {
    height: '42px',
    border: 0,
    borderRadius: '10px',
    backgroundColor: '#f8ab1d',
    color: '#ffffff',
    cursor: 'pointer',
    fontSize: '16px',
    fontWeight: 600,
  },
  profile: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flex: '0 0 auto',
    padding: '22px 24px',
    borderTop: '1px solid #e7eaf0',
  },
  avatar: {
    display: 'grid',
    width: '42px',
    height: '42px',
    flex: '0 0 42px',
    placeItems: 'center',
    borderRadius: '999px',
    backgroundColor: '#050505',
    color: '#ffffff',
    fontSize: '15px',
    fontWeight: 600,
  },
  profileName: {
    margin: 0,
    color: '#090909',
    fontSize: '17px',
    fontWeight: 600,
    lineHeight: 1.2,
  },
  profilePlan: {
    margin: '6px 0 0',
    color: '#aeb5c0',
    fontSize: '14px',
    lineHeight: 1.2,
  },
} satisfies Record<string, CSSProperties>
