import type { CSSProperties } from 'react'
import { vars } from '@/styles/theme/tokens.css'

export const styles = {
  aside: {
    display: 'flex',
    width: '280px',
    height: '100vh',
    flexDirection: 'column',
    borderRight: `1px solid ${vars.color.gray.lighter}`,
    backgroundColor: vars.color.card.primary,
    color: vars.color.gray.darkest,
    fontFamily: vars.fontFamily.body,
    overflow: 'hidden',
    position: 'sticky',
    top: 0,
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    height: '72px',
    flex: '0 0 72px',
    padding: '0 24px',
    borderBottom: `1px solid ${vars.color.gray.lighter}`,
    color: vars.color.base.black,
    fontFamily: vars.fontFamily.brand,
    fontSize: vars.fontSize['3xl'],
    fontWeight: 400,
    letterSpacing: '4px',
    lineHeight: 1,
  },
  brandAccent: {
    color: vars.color.primary.main,
  },
  navigation: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    gap: '14px',
    minHeight: 0,
    padding: '18px 18px 12px',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  sectionLabel: {
    color: vars.color.gray.light,
    fontSize: vars.fontSize.sm,
    fontWeight: 400,
    letterSpacing: '0',
    lineHeight: 1,
    textTransform: 'uppercase',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    minHeight: '34px',
    padding: '0 12px 0 16px',
    borderRadius: '8px',
    color: vars.color.gray.main,
    fontSize: vars.fontSize.md,
    fontWeight: 400,
    lineHeight: 1,
    textDecoration: 'none',
  },
  activeItem: {
    backgroundColor: vars.color.base.secondary,
    color: vars.color.gray.darkest,
  },
  icon: {
    width: '18px',
    height: '18px',
    flex: '0 0 18px',
    objectFit: 'contain',
  },
  badge: {
    display: 'grid',
    width: '28px',
    height: '28px',
    marginLeft: 'auto',
    placeItems: 'center',
    borderRadius: '999px',
    backgroundColor: vars.color.base.black,
    color: vars.color.base.white,
    fontSize: vars.fontSize.sm,
    fontWeight: 700,
    lineHeight: 1,
  },
  proCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    flex: '0 0 auto',
    margin: '6px 18px 18px',
    padding: '18px',
    borderRadius: '12px',
    backgroundColor: vars.color.card.secondary,
  },
  proTitle: {
    margin: 0,
    color: vars.color.base.black,
    fontSize: vars.fontSize.lg,
    fontWeight: 600,
    lineHeight: 1.2,
  },
  proText: {
    margin: 0,
    color: vars.color.gray.main,
    fontSize: vars.fontSize.sm,
    lineHeight: 1.35,
  },
  proButton: {
    height: '42px',
    border: 0,
    borderRadius: '10px',
    backgroundColor: vars.color.button.bgPrimary,
    color: vars.color.button.bgPrimaryLabel,
    cursor: 'pointer',
    fontSize: vars.fontSize.md,
    fontWeight: 600,
  },
  profile: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flex: '0 0 auto',
    padding: '22px 24px',
    borderTop: `1px solid ${vars.color.gray.lighter}`,
  },
  avatar: {
    display: 'grid',
    width: '42px',
    height: '42px',
    flex: '0 0 42px',
    placeItems: 'center',
    borderRadius: '999px',
    backgroundColor: vars.color.base.black,
    color: vars.color.base.white,
    fontSize: vars.fontSize.sm,
    fontWeight: 600,
  },
  profileName: {
    margin: 0,
    color: vars.color.base.black,
    fontSize: vars.fontSize.md,
    fontWeight: 600,
    lineHeight: 1.2,
  },
  profilePlan: {
    margin: '6px 0 0',
    color: vars.color.gray.light,
    fontSize: vars.fontSize.sm,
    lineHeight: 1.2,
  },
} satisfies Record<string, CSSProperties>
